controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      
diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["front_left_joint", "back_left_joint"]
    right_wheel_names: ["front_right_joint", "back_right_joint"]
    wheel_separation: 0.14
    wheel_radius: 0.03
    publish_rate: 50.0
    base_frame_id: base_footprint
    odom_frame_id: odom
    enable_odom_tf: true
    use_stamped_vel: false
    open_loop: false
    position_feedback: false